giving api key at multiple_instances

diff --git a/start b/start
--- a/start
+++ b/start
@@ -38,10 +38,10 @@ if [[ ! -f bin/hummingbot_quickstart.py ]]; then
 fi
 
 # Check if the hummingbot conda environment is activated
-# if [[ $CONDA_DEFAULT_ENV != "hummingbot" ]]; then
-#     echo "Error: 'hummingbot' conda environment is not activated. Please activate it and try again."
-#     exit 1
-# fi
+if [[ $CONDA_DEFAULT_ENV != "hummingbot" ]]; then
+    echo "Error: 'hummingbot' conda environment is not activated. Please activate it and try again."
+    exit 1
+fi
 
 # Build the command to run
 CMD="python ./bin/hummingbot_quickstart.py"
